services:
  - type: web
    name: workout-tracker
    env: node
    buildCommand: |
      npm install
      npm install --save-dev typescript @types/react @types/node
      npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXTAUTH_URL
        value: ${NEXTAUTH_URL}
      - key: NEXTAUTH_SECRET
        value: ${NEXTAUTH_SECRET}
      - key: GITHUB_ID
        value: ${GITHUB_ID}
      - key: GITHUB_SECRET
        value: ${GITHUB_SECRET}
    nodeVersion: 18.17.0