services:
  - type: web
    name: workout-tracker
    env: node
    buildCommand: npm install --legacy-peer-deps && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_BASE_URL
        value: https://your-app-name.onrender.com
    autoDeploy: true