services:
  - type: web
    name: workout-tracker
    env: node
    buildCommand: NODE_ENV=production npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_BASE_URL
        value: https://your-app-name.onrender.com
      - key: NEXT_PUBLIC_API_URL
        value: https://your-app-name.onrender.com/api
    autoDeploy: true